### ISSUE TITLE
[Feature Request] Change the tray icon depending on the status of the connection

### ISSUE THREAD

**Issue by PonasKovas** [dopefishh/netctl-tray#1]
First of all, thank you for making this.

The tray icon is kinda useless. It would be very cool if it changed when no profile is active, when a profile is active but there's no internet, and when a profile is active depending on the signal strength.

So basically, every 5 seconds or something, the program could:
 - Check if there are any profiles active (If not, change the tray icon to something with an X mark or something)
 - Check if there's internet, by pinging google.com probably. If there's no internet, change the icon to something with an ! mark)
 - Check the signal strength. AFAIK `iwconfig` gives this information.

I'm here to help, even though I'm not that experienced with `qt`, `python` and all this stuff.

**Comment by PonasKovas** [comment]
> Check if there are any profiles active (If not, change the tray icon to something with an X mark or something)

This could also be done using netctl hooks I think.

**Comment by dopefishh** [comment]
Thanks for the feedback, I don't run this tool anymore since I don't use netctl anymore. However, feel free to submit patches or I can transfer the repo.

**Comment by PonasKovas** [comment]
Ahh.. In that case I guess I will make my own tray app in Rust, as I don't really like Python.

**Comment by PonasKovas** [comment]
@dopefishh could you please consider removing this application from the AUR. to avoid confusion with https://aur.archlinux.org/packages/netctl-tray/ as it has more features and is maintained?
